language: node_js
node_js: "node"

addons:
  apt:
    packages:
    - mono

cache:
  directories:
  - website/node_modules

branches:
  only:
  - src
  - /^greenkeeper.*$/

install:
  - wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb && sudo dpkg -i crowdin.deb

  - wget https://github.com/dotnet/docfx/releases/latest/download/docfx.zip
  - unzip docfx.zip

  - git config --global user.name "Travis CI"
  - git config --global user.email "contact@nfive.io"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc

  - mkdir api/src
  - git -C api/src clone https://github.com/NFive/NFive.git
  - git -C api/src clone https://github.com/NFive/SDK.Core.git
  - git -C api/src clone https://github.com/NFive/SDK.Client.git
  - git -C api/src clone https://github.com/NFive/SDK.Server.git
  - git -C api/src clone https://github.com/NFive/SDK.Plugins.git

  - cd website && npm install

script:
  - cd ../api
  - mono ../docfx.exe
  - cp -r _site ../website/static/api

  - cd ../website
  - npm run write-translations
  - npm run crowdin-upload
  - npm run crowdin-download

  - GIT_USER="${GH_NAME}" npm run publish-gh-pages
